### ISSUE TITLE
Güncellik sorusu

### ISSUE THREAD

**Issue by hwpplayer1** [boratanrikulu/sistem-yonetimi#7]
Ben de UNIX eğitimi tasarlıyorum, dilerseniz sizin eserinizden başlayıp sonra farklı arkadaşları dahil edelim. 

Teşekkürler.

**Comment by boratanrikulu** [comment]
Merhaba,

Issue'da ne demek istediğinizi tam olarak anlayamadım.

Unix hakkında bir doküman serisi oluşturacaksınız sanırım. Bu repo'daki yazıları istediğiniz gibi kullanabilirsiniz, bir sakıncası yok.
Güncellik konusu hakkında; yazılar 2 sene önce yazıldı büyük ölçüde. Fakat bahsi geçen konular (protokoller vs) büyük ölçüde halen güncelliğini koruyordur diye ön görüyorum. Yine kullanacağız yazılarda güncelliğini irdeleyip yaklaşım sağlayabilirsiniz.

Kolay gelsin.

**Comment by hwpplayer1** [comment]
Teşekkürler, demek istediğim önce sizin eserinizin kapsamını derinleştirelim sonra ben bunu daha farklı ele alacağım. Yoksa çatallayıp düzenlemesi sorun değil.

Ben şimdiden bahsettiğim gibi araştırmaya başlıyorum. Görüşmek dileğiyle
